FROM python:3.9-slim

WORKDIR /app
COPY . .
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install netcat-traditional

ENTRYPOINT ["./entrypoint.sh"]

CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]