# Generated by Django 4.2 on 2025-07-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('kitchen_staff', 'Kitchen Staff'), ('manager', 'Manager'), ('restaurant_owner', 'Restaurant Owner')], default='customer', max_length=50),
        ),
    ]
