# Generated by Django 4.2 on 2025-08-03 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='order_participant_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
