# Generated by Django 4.2 on 2025-08-01 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
