# Generated by Django 4.2 on 2025-07-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('workday_open_hour', models.TimeField(blank=True, null=True)),
                ('workday_close_hour', models.TimeField(blank=True, null=True)),
                ('weekend_open_hour', models.TimeField(blank=True, null=True)),
                ('weekend_close_hour', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
